#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Dejavu.Models;

namespace Dejavu.Models	
{
	[System.Serializable()]
	public partial class ProgramRatings : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private long _id;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private int _programId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int ProgramId
		{
			get
			{
				return this._programId;
			}
			set
			{
				if(this._programId != value)
				{
					this.OnPropertyChanging("ProgramId");
					this._programId = value;
					this.OnPropertyChanged("ProgramId");
				}
			}
		}
		
		private int _rating;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if(this._rating != value)
				{
					this.OnPropertyChanging("Rating");
					this._rating = value;
					this.OnPropertyChanged("Rating");
				}
			}
		}
		
		private Program _program;
		public virtual Program Program
		{
			get
			{
				return this._program;
			}
			set
			{
				if(this._program != value)
				{
					this.OnPropertyChanging("Program");
					this._program = value;
					this.OnPropertyChanged("Program");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public ProgramRatings()
		{
		}
		
		protected ProgramRatings(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt64("Id");
			this.ProgramId = info.GetInt32("ProgramId");
			this.Rating = info.GetInt32("Rating");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(long));
			info.AddValue("ProgramId", this.ProgramId, typeof(int));
			info.AddValue("Rating", this.Rating, typeof(int));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
