#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Dejavu.Models;

namespace Dejavu.Models	
{
	[System.Serializable()]
	public partial class ProgramReviews : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private long _id;
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual long Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _postedBy;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string PostedBy
		{
			get
			{
				return this._postedBy;
			}
			set
			{
				if(this._postedBy != value)
				{
					this.OnPropertyChanging("PostedBy");
					this._postedBy = value;
					this.OnPropertyChanged("PostedBy");
				}
			}
		}
		
		private string _chapter;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Chapter
		{
			get
			{
				return this._chapter;
			}
			set
			{
				if(this._chapter != value)
				{
					this.OnPropertyChanging("Chapter");
					this._chapter = value;
					this.OnPropertyChanged("Chapter");
				}
			}
		}
		
		private string _review;
		[System.ComponentModel.DataAnnotations.StringLength(255)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Review
		{
			get
			{
				return this._review;
			}
			set
			{
				if(this._review != value)
				{
					this.OnPropertyChanging("Review");
					this._review = value;
					this.OnPropertyChanged("Review");
				}
			}
		}
		
		private int _programId;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int ProgramId
		{
			get
			{
				return this._programId;
			}
			set
			{
				if(this._programId != value)
				{
					this.OnPropertyChanging("ProgramId");
					this._programId = value;
					this.OnPropertyChanged("ProgramId");
				}
			}
		}
		
		private DateTime _dateCreated;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if(this._dateCreated != value)
				{
					this.OnPropertyChanging("DateCreated");
					this._dateCreated = value;
					this.OnPropertyChanged("DateCreated");
				}
			}
		}
		
		private Program _program;
		public virtual Program Program
		{
			get
			{
				return this._program;
			}
			set
			{
				if(this._program != value)
				{
					this.OnPropertyChanging("Program");
					this._program = value;
					this.OnPropertyChanged("Program");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public ProgramReviews()
		{
		}
		
		protected ProgramReviews(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt64("Id");
			this.PostedBy = info.GetString("PostedBy");
			this.Chapter = info.GetString("Chapter");
			this.Review = info.GetString("Review");
			this.ProgramId = info.GetInt32("ProgramId");
			this.DateCreated = (DateTime)info.GetValue("DateCreated", typeof(DateTime));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(long));
			info.AddValue("PostedBy", this.PostedBy, typeof(string));
			info.AddValue("Chapter", this.Chapter, typeof(string));
			info.AddValue("Review", this.Review, typeof(string));
			info.AddValue("ProgramId", this.ProgramId, typeof(int));
			info.AddValue("DateCreated", this.DateCreated, typeof(DateTime));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
