#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Dejavu.Models;

namespace Dejavu.Models	
{
	[System.Serializable()]
	public partial class Program : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged, System.Runtime.Serialization.ISerializable
	{
		private int _id;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _name;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				if(this._name != value)
				{
					this.OnPropertyChanging("Name");
					this._name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
		
		private DateTime _dateHeld;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateHeld
		{
			get
			{
				return this._dateHeld;
			}
			set
			{
				if(this._dateHeld != value)
				{
					this.OnPropertyChanging("DateHeld");
					this._dateHeld = value;
					this.OnPropertyChanged("DateHeld");
				}
			}
		}
		
		private string _bannerUrl;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string BannerUrl
		{
			get
			{
				return this._bannerUrl;
			}
			set
			{
				if(this._bannerUrl != value)
				{
					this.OnPropertyChanging("BannerUrl");
					this._bannerUrl = value;
					this.OnPropertyChanged("BannerUrl");
				}
			}
		}
		
		private string _videoUrl;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string VideoUrl
		{
			get
			{
				return this._videoUrl;
			}
			set
			{
				if(this._videoUrl != value)
				{
					this.OnPropertyChanging("VideoUrl");
					this._videoUrl = value;
					this.OnPropertyChanged("VideoUrl");
				}
			}
		}
		
		private DateTime _dateCreated;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if(this._dateCreated != value)
				{
					this.OnPropertyChanging("DateCreated");
					this._dateCreated = value;
					this.OnPropertyChanged("DateCreated");
				}
			}
		}
		
		private string _description;
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				if(this._description != value)
				{
					this.OnPropertyChanging("Description");
					this._description = value;
					this.OnPropertyChanged("Description");
				}
			}
		}
		
		private IList<ProgramReviews> _programReviews = new List<ProgramReviews>();
		public virtual IList<ProgramReviews> ProgramReviews
		{
			get
			{
				return this._programReviews;
			}
		}
		
		private IList<ProgramTestimonies> _programTestimonies = new List<ProgramTestimonies>();
		public virtual IList<ProgramTestimonies> ProgramTestimonies
		{
			get
			{
				return this._programTestimonies;
			}
		}
		
		private IList<ProgramRatings> _programRatings = new List<ProgramRatings>();
		public virtual IList<ProgramRatings> ProgramRatings
		{
			get
			{
				return this._programRatings;
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region ISerializable Implementation
		
		public Program()
		{
		}
		
		protected Program(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.Id = info.GetInt32("Id");
			this.Name = info.GetString("Name");
			this.DateHeld = (DateTime)info.GetValue("DateHeld", typeof(DateTime));
			this.BannerUrl = info.GetString("BannerUrl");
			this.VideoUrl = info.GetString("VideoUrl");
			this.DateCreated = (DateTime)info.GetValue("DateCreated", typeof(DateTime));
			this.Description = info.GetString("Description");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("Id", this.Id, typeof(int));
			info.AddValue("Name", this.Name, typeof(string));
			info.AddValue("DateHeld", this.DateHeld, typeof(DateTime));
			info.AddValue("BannerUrl", this.BannerUrl, typeof(string));
			info.AddValue("VideoUrl", this.VideoUrl, typeof(string));
			info.AddValue("DateCreated", this.DateCreated, typeof(DateTime));
			info.AddValue("Description", this.Description, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
